  motioneye:
    image: "ccrisan/motioneye:master-armhf"
    container_name: "motioneye"
    restart: unless-stopped
    ports:
      - 8765:8765 
      - 8081:8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/motioneye/etc:/etc/motioneye
      - /mnt/motioneye/var:/var/lib/motioneye
      - /mnt/ssl:/ssl
    #devices:
    #  - "/dev/video0:/dev/video0"

