  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - /mnt/tasmoadmin/data:/data
      - /mnt/ssl:/ssl   
